# Generated by Django 3.2.24 on 2024-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={},
        ),
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='selling_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
