# Generated by Django 3.2.24 on 2024-02-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240225_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
