# Generated by Django 3.2.24 on 2024-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240227_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'Kilograms'), ('mL', 'Milliliters'), ('L', 'Liters'), ('pc', 'Piece')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
